### PR TITLE
Fixing the spelling error

### PR DESCRIPTION
**Pull request by Muhammad-Adil-Shahid-1054**
Corrected the grammatical spelling and spacing error in the aggregation part  of the documentation.

### CODE REVIEW

**Comment by dehowef** [comment]
Good you can condense your commit title so it fits on one line and write a description instead

**Review by dehowef — CHANGES_REQUESTED** [review]
^

**Comment by Muhammad-Adil-Shahid-1054** [comment]
@dehowef I have update my commit title. Please review

**Comment by dehowef** [comment]
Can you fix the description @Muhammad-Adil-Shahid-1054

**Comment by Muhammad-Adil-Shahid-1054** [comment]
@dehowef Done

**Pull request merged**
