### PR TITLE
Update New-web

### PR DESCRIPTION
**Pull request by dpdjvhxm**
Update meta description

Update title name in index-page

Update Image resource(Landing page banner, Article images)

Update FAQ Page:  Add Q14 ~ Q17

### CODE REVIEW

**Review by MuhammadTahaNaveed — CHANGES_REQUESTED** [review]
@dpdjvhxm Please write a meaningful commit message with extended description of changes introduced by this PR.

**Comment by dpdjvhxm** [comment]
@MuhammadTahaNaveed 

Thanks for the review

Update meta description : gatsby-config.js
- description: "Since May 2022, Apache AGE® is a Top-Level Project at the Apache Software Foundation, born from AgensGraph and developed by Bitnine Global Inc. since 2019. Donated to Apache in April 2020, it enhances graph database capabilities under the Apache License 2.0.",

Update title name in index-page: src/pages/index.md
- Apache AGE | Graph Database Extension for PostgreSQL

Update Image resource(Landing page banner, Article images)
- replace image for size reduce

Update FAQ Page: Add Q14 ~ Q17
- Updated questions in FAQ page (https://github.com/apache/age-website/pull/297/files#diff-6f03dca09f952eeb1c02b70721c79a9e4060de1618404a5511d6f56a1ee8d7b8)

**Comment by MuhammadTahaNaveed** [comment]
@dpdjvhxm Thank you for explaining the changes. However, my request was to change the commit message. If you are not familiar about how to change the commit message, please see [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message).

As a sample for writing meaningful commit message, you can refer to the screenshot below:

image

**Comment by dpdjvhxm** [comment]
@MuhammadTahaNaveed 

I check the link and try it. Is that right way to fix it? 
image

**Comment by MuhammadTahaNaveed** [comment]
> @MuhammadTahaNaveed
> 
> I check the link and try it. Is that right way to fix it? image

You made a new commit with the same changes rather than amending the previous commit. But it will work for now 👍🏻 . Just remember to write **good commit messages with extended description** in your **future PRs** as well. Thank you.

**Comment by dpdjvhxm** [comment]
@MuhammadTahaNaveed 
Thanks for your feedback and kind help. now I understand how it works but still need to learn about it.
I will keep that in my mind. 👍 
Thanks

**Pull request merged**
