### PR TITLE
Modified guide/index.html

### PR DESCRIPTION
**Pull request by MatheusFarias03**
Set the html file to be prettier and more organized, and also updated the coding style for AGE. Hope this is fine the way it is, it was quite an adventure fixing the entire file. But if anything is wrong, please let me know and I will update it.

### CODE REVIEW

**Comment by MuhammadTahaNaveed** [comment]
@MatheusFarias03 Unfortunately, you updated wrong branch(that was for older website i guess) lol.

The deployed website is on the branch `new-web`. Most probably you would need to update [this file](https://github.com/apache/age-website/blob/new-web/src/pages/contribution/guide.md).

**Comment by MatheusFarias03** [comment]
Oh... well, at least it's a markdown file there

**Comment by MatheusFarias03** [comment]
Created a new PR: #198

**Comment by dehowef** [comment]
This was resolved in a later PR. Closing this one

**Pull request closed without merging**
